//
//  PixelIconview.swift
//  Chakras
//
//  Created by Pierre Untas on 11/11/2024.
//

import SwiftUI

struct PixelFoxView: View {
    let pixelSize: CGFloat = 2.5
    let spacing: CGFloat = 0.5
    
    let icons: [String: [[Color]]] = [
        "fox": [
            [.clear, .clear, .clear, .clear, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .black, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .brown, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .black, .brown, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .brown, .black, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .black, .black, .brown, .brown, .white, .brown, .brown, .brown, .brown, .brown, .brown, .white, .brown, .brown, .black, .black, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .black, .black, .black, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .black, .black, .black, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .black, .white, .white, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .white, .white, .black, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .black, .white, .white, .white, .white, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .white, .white, .white, .white, .black, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .black, .white, .white, .white, .white, .white, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .white, .white, .white, .white, .white, .black, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .brown, .brown, .brown, .brown, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .brown, .brown, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .brown, .brown, .brown, .black, .black, .white, .white, .white, .white, .white, .white, .white, .black, .black, .brown, .brown, .brown, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear],
            [.clear, .clear, .white, .white, .white, .brown, .brown, .brown, .black, .white, .white, .black, .black, .white, .white, .white, .white, .black, .white, .white, .black, .brown, .brown, .brown, .brown, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear],
            [.clear, .white, .white, .brown, .brown, .brown, .brown, .brown, .black, .black, .black, .black, .black, .white, .white, .white, .white, .black, .black, .black, .black, .brown, .brown, .brown, .brown, .brown, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear],
            [.clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear],
            [.clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .black, .black, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .black, .black, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .black, .black, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .black, .black, .black, .black, .black, .black, .black, .black, .black, .black, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .black, .black, .black, .black, .black, .black, .black, .black, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .black, .black, .black, .black, .black, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .black, .black, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .brown, .brown, .white, .white, .brown, .brown, .brown, .brown, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .brown, .brown, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .white, .brown, .clear, .brown, .brown, .brown, .brown, .brown, .brown, .brown, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
            [.clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .clear, .clear, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .white, .white, .white, .white, .white, .clear, .clear, .white, .white, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear, .clear],
        ]
    ]
    
    let iconName: String
    
    var colorMapping: [Color: Color] = [
        .white: .white,   // Exemple : remplace le blanc par du bleu
        .black: .black,   // Exemple : remplace le noir par du gris
        .brown: .brown, // Exemple : remplace le marron par de l'orange
        .clear: .clear   // Garde les pixels transparents
        ]

        var body: some View {
            VStack(spacing: spacing) {
                if let pixels = icons[iconName] {
                    ForEach(0..<pixels.count, id: \.self) { row in
                        HStack(spacing: spacing) {
                            ForEach(0..<pixels[row].count, id: \.self) { col in
                                Rectangle()
                                    .fill(colorMapping[pixels[row][col], default: .clear]) // Utilise le mappage des couleurs
                                    .frame(width: pixelSize, height: pixelSize)
                            }
                        }
                    }
                } else {
                    Text("Icône non trouvée")
                        .foregroundColor(.red)
                }
            }
        }
    }
